name: Copy Docker Hub Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  copy-images:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Elasticsearch
      - name: Pull docker hub image for elasticsearch
        run: docker pull bitnamilegacy/elasticsearch:8.6.2-debian-11-r10

      - name: Tag image for GHCR
        run: docker tag bitnamilegacy/elasticsearch:8.6.2-debian-11-r10 ghcr.io/${{ github.repository_owner }}/folio-elasticsearch:8.6.2-debian-11-r10

      - name: Push image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/folio-elasticsearch:8.6.2-debian-11-r10

      
      - name: Pull docker hub image for os-shell
        run: docker pull bitnamilegacy/os-shell:latest

      - name: Tag image for GHCR
        run: docker tag bitnamilegacy/os-shell:latest ghcr.io/${{ github.repository_owner }}/bitnamilegacy-os-shell:latest

      - name: Push image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/bitnamilegacy-os-shell:latest

      
      - name: Pull docker hub image for elasticsearch-exporter
        run: docker pull bitnamilegacy/elasticsearch-exporter:latest
      
      - name: Tag image for GHCR
        run: docker tag bitnamilegacy/elasticsearch-exporter:latest ghcr.io/${{ github.repository_owner }}/bitnamilegacy-elasticsearch-exporter:latest

      - name: Push image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/bitnamilegacy-elasticsearch-exporter:latest
      
      # Kafka
      - name: Pull docker hub image for kafka
        run: docker pull bitnamilegacy/bitnamilegacy/kafka:3.9.0-debian-12-r1
      
      - name: Tag image for GHCR
        run: docker tag bitnamilegacy/bitnamilegacy/kafka:3.9.0-debian-12-r1 ghcr.io/${{ github.repository_owner }}/bitnamilegacy-kafka:3.9.0-debian-12-r1

      - name: Push image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/bitnamilegacy-kafka:3.9.0-debian-12-r1

      
      - name: Pull docker hub image for kafka-jmx-exporter
        run: docker pull bitnamilegacy/kafka-jmx-exporter:latest  

      - name: Tag image for GHCR
        run: docker tag bitnamilegacy/kafka-jmx-exporter:latest ghcr.io/${{ github.repository_owner }}/bitnamilegacy-jmx-exporter:latest
      
      - name: Push image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/bitnamilegacy-jmx-exporter:latest

      # Postfix
      - name: Pull docker hub image for postfix
        run: docker pull bitnamilegacy/postfix:latest

      - name: Tag image for GHCR
        run: docker tag bitnamilegacy/postfix:latest ghcr.io/${{ github.repository_owner }}/bitnamilegacy-postfix:latest
      
      - name: Push image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/bitnamilegacy-postfix:latest
